### ISSUE TITLE
Flatcar and Kubevirt

### ISSUE THREAD

**Issue by dirien** [flatcar/Flatcar#406]
## Description

I tried to install kubevirt on a kubernetes cluster, where the nodes are all use flatcar linux as a OS.

During the install of the pods, i get following error message:

```bash
➜  ~ k logs virt-handler-lxxjz -n kubevirt
{"component":"virt-handler","hostname":"shoot--p1t9r9jxg1--kubevirt-worker-tlx5n-z1-5df6d-qmtzl","level":"info","pos":"virt-handler.go:183","timestamp":"2021-05-28T19:31:02.128104Z"}
W0528 19:31:02.131403   63743 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"component":"virt-handler","level":"info","msg":"set verbosity to 2","pos":"virt-handler.go:427","timestamp":"2021-05-28T19:31:02.153896Z"}
{"component":"virt-handler","level":"info","msg":"Starting collector: node name=shoot--p1t9r9jxg1--kubevirt-worker-tlx5n-z1-5df6d-qmtzl","pos":"prometheus.go:556","timestamp":"2021-05-28T19:31:02.153941Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer CRDInformer","pos":"virtinformers.go:261","timestamp":"2021-05-28T19:31:02.154020Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer kubeVirtInformer","pos":"virtinformers.go:261","timestamp":"2021-05-28T19:31:02.154067Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer vmiInformer-sources","pos":"virtinformers.go:261","timestamp":"2021-05-28T19:31:02.154087Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer vmiInformer-targets","pos":"virtinformers.go:261","timestamp":"2021-05-28T19:31:02.154114Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer extensionsKubeVirtCAConfigMapInformer","pos":"virtinformers.go:261","timestamp":"2021-05-28T19:31:02.154133Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer configMapInformer","pos":"virtinformers.go:261","timestamp":"2021-05-28T19:31:02.154147Z"}
{"component":"virt-handler","level":"info","msg":"metrics: max concurrent requests=3","pos":"virt-handler.go:436","timestamp":"2021-05-28T19:31:02.154221Z"}
{"component":"virt-handler","level":"info","msg":"certificate with common name 'kubevirt.io:system:client:virt-handler' retrieved.","pos":"cert-manager.go:198","timestamp":"2021-05-28T19:31:02.154506Z"}
{"component":"virt-handler","level":"info","msg":"certificate with common name 'kubevirt.io:system:node:virt-handler' retrieved.","pos":"cert-manager.go:198","timestamp":"2021-05-28T19:31:02.154517Z"}
{"component":"virt-handler","level":"info","msg":"SELinux is reported as 'permissive'","pos":"virt-handler.go:335","timestamp":"2021-05-28T19:31:02.160496Z"}
{"component":"virt-handler","level":"info","msg":"Updating cluster config from KubeVirt to resource version '9394'","pos":"config-map.go:516","timestamp":"2021-05-28T19:31:02.161825Z"}
{"component":"virt-handler","level":"info","msg":"set verbosity to 2","pos":"virt-handler.go:427","timestamp":"2021-05-28T19:31:02.161856Z"}
{"component":"virt-handler","level":"warning","msg":"Permissive mode, ignoring 'semodule' failure: out: \"libsemanage.semanage_create_store: Could not access module store at /var/lib/selinux/mcs, or it is not a directory. (Read-only file system).\\nlibsemanage.semanage_direct_connect: could not establish direct connection (Read-only file system).\\n/sbin/semodule:  Could not connect to policy handler\\n\", error: exit status 1","pos":"labels.go:102","timestamp":"2021-05-28T19:31:02.168777Z"}
panic: error relabeling required files: error relabeling file /dev/net/tun with label system_u:object_r:container_file_t:s0. Reason: exit status 1

goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000236300)
	cmd/virt-handler/virt-handler.go:346 +0x2c94
main.main()
	cmd/virt-handler/virt-handler.go:546 +0x6e
```

There are other discussions (https://github.com/kubevirt/kubevirt/issues/5298#issuecomment-815580390) but i cant really see where the issue is? Is there something I need to do in Flatcar or is kubevirt need to change the way they handle certain situations?

https://github.com/kubevirt/kubevirt/issues/5736

## Impact

Can not install kubevirt

## Environment and steps to reproduce

1. **Set-up**: Kuberntes with Flatcar nodes
2. **Task**: Install kubevirt https://kubevirt.io/quickstart_cloud/
3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. [ requested the start of a new pod or container ]
  b. [ container image downloaded ]
4. **Error**: https://github.com/kubevirt/kubevirt/issues/5736

## Expected behavior

kubevirt is up and running.

**Comment by dirien** [comment]
close, as no feedback.

**Comment by pothos** [comment]
The linked issue has the explanation: kubevirt's detection of the SELinux mode is different and the workaround is to disable SELinux from the kernel command line instead of the `/etc/selinux/config` file: https://github.com/kubevirt/kubevirt/issues/5298#issuecomment-817670974

**Comment by dirien** [comment]
@pothos, thank you for the feedback, I appriciate this very much! ❤️

**Comment by mhmdka** [comment]
@dirien Did you manage to install kubevirt on Flatcar?
